const StableAssignment = require('../models/StableAssignment');
const FeedingSchedule = require('../models/FeedingSchedule');
const DailyTask = require('../models/DailyTask');

const CHECK_INTERVAL_MS = 60 * 60 * 1000; // hourly is enough for day-granularity tasks

// Used when a horse has an approved ration for a slot but nobody set a clock time on it, and as
// the fallback stable routine for horses with no ration on file at all.
const DEFAULT_MEAL_TIMES = { morning: '06:00', noon: '11:30', evening: '17:30' };

/**
 * Auto-generates today's feeding DailyTasks for every horse that has a long-term StableAssignment
 * (horse -> caretaker), so the Head Trainer no longer has to manually assign the care work that's
 * fully predictable every single day. Situational tasks (cleaning) stay manually assigned via the
 * trainer's page; post-training icing/bathing are generated by the session evaluation instead,
 * since only that knows how hard the horse actually worked.
 *
 * One task per meal, not one per day. A single "feed the horse" task carried no time of day, which
 * meant nothing downstream could tell whether the horse had eaten two hours ago or ten minutes ago
 * — and that gap is exactly what the training readiness check needs in order to know whether the
 * horse can safely be worked.
 *
 * Runs on a periodic check rather than a once-a-day timer so it stays correct even if the server
 * restarts mid-day (common on Render's free tier, which sleeps after inactivity) — each check just
 * ensures today's tasks exist, so it's safe to run repeatedly without duplicating.
 */
function startDailyTaskGenerator() {
  console.log(`[daily-task-generator] started (checking every ${CHECK_INTERVAL_MS / 60000}min)`);

  const check = async () => {
    try {
      const assignments = await StableAssignment.find({ assignedCaretaker: { $ne: null } }).select(
        'horse assignedCaretaker'
      );
      if (assignments.length === 0) return;

      const dayStart = new Date();
      dayStart.setHours(0, 0, 0, 0);
      const dayEnd = new Date(dayStart);
      dayEnd.setDate(dayEnd.getDate() + 1);

      const schedules = await FeedingSchedule.find({
        horse: { $in: assignments.map((a) => a.horse) },
      }).select('horse mealTime timeOfDay');

      for (const assignment of assignments) {
        const horseMeals = schedules.filter((s) => String(s.horse) === String(assignment.horse));

        // No ration on file yet — keep the old behaviour of a single daily feeding task rather
        // than inventing three meals the stable never agreed to.
        const slots = horseMeals.length
          ? horseMeals.map((m) => ({ mealSlot: m.mealTime, timeOfDay: m.timeOfDay || DEFAULT_MEAL_TIMES[m.mealTime] }))
          : [{ mealSlot: null, timeOfDay: null }];

        for (const slot of slots) {
          // eslint-disable-next-line no-await-in-loop
          const existing = await DailyTask.findOne({
            horse: assignment.horse,
            assignedTo: assignment.assignedCaretaker,
            taskType: 'feeding',
            mealSlot: slot.mealSlot,
            scheduledDate: { $gte: dayStart, $lt: dayEnd },
          });
          if (existing) continue;

          const scheduledDate = new Date(dayStart);
          if (slot.timeOfDay) {
            const [hh, mm] = slot.timeOfDay.split(':').map(Number);
            if (Number.isFinite(hh) && Number.isFinite(mm)) scheduledDate.setHours(hh, mm, 0, 0);
          }

          // eslint-disable-next-line no-await-in-loop
          await DailyTask.create({
            horse: assignment.horse,
            assignedTo: assignment.assignedCaretaker,
            taskType: 'feeding',
            mealSlot: slot.mealSlot,
            scheduledDate,
            status: 'pending',
          });
        }
      }
    } catch (err) {
      console.error('[daily-task-generator] check failed:', err.message);
    }
  };

  check(); // also run once immediately on startup, don't wait a full interval
  setInterval(check, CHECK_INTERVAL_MS);
}

module.exports = { startDailyTaskGenerator };
