const mongoose = require('mongoose');

const incidentReportSchema = new mongoose.Schema(
  {
    description: { type: String, required: true },
    images: [{ type: String }], // relative URLs served from /uploads
    severity: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' },
    reportedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const dailyTaskSchema = new mongoose.Schema(
  {
    horse: { type: mongoose.Schema.Types.ObjectId, ref: 'Horse', required: true },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    taskType: {
      type: String,
      enum: ['feeding', 'cleaning', 'bathing', 'icing'],
      required: true,
    },
    // Which meal a feeding task covers. Null for every other task type. Without it one horse's
    // three meals a day were indistinguishable, so nothing could tell whether the horse had
    // eaten recently enough — or long enough ago — to be worked.
    mealSlot: { type: String, enum: ['morning', 'noon', 'evening'], default: null },
    // Set when the task was generated by a training session (post-work icing, washing down)
    // rather than assigned by hand, so the groom can see why it appeared.
    trainingSession: { type: mongoose.Schema.Types.ObjectId, ref: 'TrainingSession', default: null },
    note: { type: String }, // the trainer's instruction riding along with the task
    scheduledDate: { type: Date, required: true, default: Date.now },
    status: { type: String, enum: ['pending', 'completed', 'skipped'], default: 'pending' },
    completedAt: { type: Date },
    // What the groom saw while doing the work. Optional on purpose: completing a task without it
    // behaves exactly as before, so this can ship before any screen collects it.
    observation: {
      appetite: { type: String, enum: ['full', 'partial', 'refused'], default: null },
      amountEatenPercent: { type: Number, min: 0, max: 100 },
      behaviourNote: { type: String },
      recordedAt: { type: Date },
    },
    incidentReport: incidentReportSchema,
  },
  { timestamps: true }
);

module.exports = mongoose.model('DailyTask', dailyTaskSchema);
