const mongoose = require('mongoose');
const { taskTiming } = require('../utils/taskTiming');

const incidentReportSchema = new mongoose.Schema(
  {
    description: { type: String, required: true },
    images: [{ type: String }], // relative URLs served from /uploads
    severity: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' },
    reportedAt: { type: Date, default: Date.now },
    // A report used to end at the vet's notification bell: nothing recorded whether anyone had
    // looked at the horse. Open until the vet picks it up and closes it (or files an exam).
    status: { type: String, enum: ['open', 'acknowledged', 'resolved'], default: 'open' },
    handledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    response: { type: String }, // what the vet found / told the stable to do
    resolvedAt: { type: Date, default: null },
    healthRecord: { type: mongoose.Schema.Types.ObjectId, ref: 'HealthRecord', default: null },
  },
  { _id: false }
);

const dailyTaskSchema = new mongoose.Schema(
  {
    horse: { type: mongoose.Schema.Types.ObjectId, ref: 'Horse', required: true },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    taskType: {
      type: String,
      // medication / monitoring are the vet's care orders (see health/treatmentCare.service.js).
      // 'other' is any job the list doesn't name; its note says what it is.
      enum: ['feeding', 'cleaning', 'bathing', 'icing', 'medication', 'monitoring', 'other'],
      required: true,
    },
    // Who the work comes from: assigned by hand (trainer/manager), ordered by the vet through a
    // treatment, or generated by the system (daily meals, post-session care).
    source: { type: String, enum: ['trainer', 'vet', 'system'], default: 'trainer' },
    // The treatment a vet's care order belongs to; it ends when the treatment does.
    treatment: { type: mongoose.Schema.Types.ObjectId, ref: 'Treatment', default: null },
    // Which meal a feeding task covers. Null for every other task type. Without it one horse's
    // three meals a day were indistinguishable, so nothing could tell whether the horse had
    // eaten recently enough — or long enough ago — to be worked.
    mealSlot: { type: String, enum: ['morning', 'noon', 'evening'], default: null },
    // Set when the task was generated by a training session (post-work icing, washing down)
    // rather than assigned by hand, so the groom can see why it appeared.
    trainingSession: { type: mongoose.Schema.Types.ObjectId, ref: 'TrainingSession', default: null },
    note: { type: String }, // the trainer's instruction riding along with the task
    // Time of day of a vet's dose ("08:00"); such a task can be recorded around that time only.
    dueTime: { type: String, default: null },
    // What doing the task uses up, taken out of stock when it is completed (a meal's ration, a dose).
    supplies: [
      {
        inventoryItem: { type: mongoose.Schema.Types.ObjectId, ref: 'InventoryItem' },
        name: { type: String },
        amount: { type: Number },
        unit: { type: String },
        _id: false,
      },
    ],
    scheduledDate: { type: Date, required: true, default: Date.now },
    status: { type: String, enum: ['pending', 'completed', 'skipped'], default: 'pending' },
    completedAt: { type: Date }, // when the work was done (the groom's clock, checked), not when the server heard
    // When the server received the record, apart from when it was done: a phone without signal sends later.
    receivedAt: { type: Date, default: null },
    // Sent more than SYNC_LATE_MINUTES after it was done (from the offline outbox).
    recordedLate: { type: Boolean, default: false },
    // The app's ids for the actions already applied, so a resend of the same action is answered, not repeated.
    opIds: { type: [String], default: [] },
    // The groom has seen the task and taken it on — for a vet's order, the trainer and manager can
    // tell "nobody has picked this up" apart from "picked up, not done yet".
    acknowledgedAt: { type: Date, default: null },
    // Set when a task is called off (status skipped): by the trainer (fasting before a race) or by
    // the groom reporting they could not do it — then with the reason (horse spat the medicine out).
    skipReason: { type: String },
    skippedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    // What the groom saw while doing the work. Optional on purpose: completing a task without it
    // behaves exactly as before, so this can ship before any screen collects it.
    observation: {
      appetite: { type: String, enum: ['full', 'partial', 'refused'], default: null },
      amountEatenPercent: { type: Number, min: 0, max: 100 },
      // Droppings and drinking are the earliest signs of colic, which is why the groom records them.
      manure: { type: String, enum: ['normal', 'dry', 'loose', 'none'], default: null },
      waterIntake: { type: String, enum: ['normal', 'high', 'low'], default: null },
      behaviourNote: { type: String },
      recordedAt: { type: Date },
    },
    incidentReport: incidentReportSchema,
  },
  // `timing` is computed, not stored, and goes out with every task so the web and mobile screens
  // show the same "open / upcoming / missed" the server enforces. `id: false` keeps the default
  // `id` virtual from being added alongside `_id`.
  { timestamps: true, id: false, toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

dailyTaskSchema.virtual('timing').get(function timing() {
  return taskTiming(this);
});

module.exports = mongoose.model('DailyTask', dailyTaskSchema);
