const mongoose = require('mongoose');

const incidentReportSchema = new mongoose.Schema(
  {
    description: { type: String, required: true },
    images: [{ type: String }], // relative URLs served from /uploads
    severity: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' },
    reportedAt: { type: Date, default: Date.now },
    // A report used to end at the vet's notification bell: nothing recorded whether anyone had
    // looked at the horse. Open until the vet picks it up and closes it (or files an exam).
    status: { type: String, enum: ['open', 'acknowledged', 'resolved'], default: 'open' },
    handledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    response: { type: String }, // what the vet found / told the stable to do
    resolvedAt: { type: Date, default: null },
    healthRecord: { type: mongoose.Schema.Types.ObjectId, ref: 'HealthRecord', default: null },
  },
  { _id: false }
);

const dailyTaskSchema = new mongoose.Schema(
  {
    horse: { type: mongoose.Schema.Types.ObjectId, ref: 'Horse', required: true },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    taskType: {
      type: String,
      // medication / monitoring are the vet's care orders (see health/treatmentCare.service.js).
      enum: ['feeding', 'cleaning', 'bathing', 'icing', 'medication', 'monitoring'],
      required: true,
    },
    // Who the work comes from: assigned by hand (trainer/manager), ordered by the vet through a
    // treatment, or generated by the system (daily meals, post-session care).
    source: { type: String, enum: ['trainer', 'vet', 'system'], default: 'trainer' },
    // The treatment a vet's care order belongs to; it ends when the treatment does.
    treatment: { type: mongoose.Schema.Types.ObjectId, ref: 'Treatment', default: null },
    // Which meal a feeding task covers. Null for every other task type. Without it one horse's
    // three meals a day were indistinguishable, so nothing could tell whether the horse had
    // eaten recently enough — or long enough ago — to be worked.
    mealSlot: { type: String, enum: ['morning', 'noon', 'evening'], default: null },
    // Set when the task was generated by a training session (post-work icing, washing down)
    // rather than assigned by hand, so the groom can see why it appeared.
    trainingSession: { type: mongoose.Schema.Types.ObjectId, ref: 'TrainingSession', default: null },
    note: { type: String }, // the trainer's instruction riding along with the task
    scheduledDate: { type: Date, required: true, default: Date.now },
    status: { type: String, enum: ['pending', 'completed', 'skipped'], default: 'pending' },
    completedAt: { type: Date },
    // What the groom saw while doing the work. Optional on purpose: completing a task without it
    // behaves exactly as before, so this can ship before any screen collects it.
    observation: {
      appetite: { type: String, enum: ['full', 'partial', 'refused'], default: null },
      amountEatenPercent: { type: Number, min: 0, max: 100 },
      // Droppings and drinking are the earliest signs of colic, which is why the groom records them.
      manure: { type: String, enum: ['normal', 'dry', 'loose', 'none'], default: null },
      waterIntake: { type: String, enum: ['normal', 'high', 'low'], default: null },
      behaviourNote: { type: String },
      recordedAt: { type: Date },
    },
    incidentReport: incidentReportSchema,
  },
  { timestamps: true }
);

module.exports = mongoose.model('DailyTask', dailyTaskSchema);
